START: Tue Oct 28 01:58:45 AM UTC 2025
JOB  : symm-mem-allreduce  ID=974915
W1028 01:58:53.096000 1670820 torch/distributed/run.py:803] 
W1028 01:58:53.096000 1670820 torch/distributed/run.py:803] *****************************************
W1028 01:58:53.096000 1670820 torch/distributed/run.py:803] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1028 01:58:53.096000 1670820 torch/distributed/run.py:803] *****************************************
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
    import click
ModuleNotFoundError: No module named 'click'
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
    import click
ModuleNotFoundError: No module named 'click'
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/symm_mem_all_reduce.py", line 4, in <module>
    import click
    import click
ModuleNotFoundError: No module named 'click'
ModuleNotFoundError: No module named 'click'
E1028 01:58:55.963000 1670820 torch/distributed/elastic/multiprocessing/api.py:882] failed (exitcode: 1) local_rank: 0 (pid: 1670926) of binary: python3
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/bin/torchrun", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 357, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/run.py", line 936, in main
    run(args)
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/run.py", line 927, in run
    elastic_launch(
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 156, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 293, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
python3 FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1670927)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1670928)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1670929)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 1670930)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 1670931)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 1670932)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 1670933)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-10-28_01:58:55
  host      : fs-mbz-gpu-873
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1670926)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
