START: Tue Oct 28 02:06:31 AM UTC 2025
JOB  : symm-mem-allreduce  ID=974926
W1028 02:06:33.920000 1673947 torch/distributed/run.py:803] 
W1028 02:06:33.920000 1673947 torch/distributed/run.py:803] *****************************************
W1028 02:06:33.920000 1673947 torch/distributed/run.py:803] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1028 02:06:33.920000 1673947 torch/distributed/run.py:803] *****************************************
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
    import triton.tools.experimental_descriptor
    import triton.tools.experimental_descriptor
    import triton.tools.experimental_descriptor
    import triton.tools.experimental_descriptor
    import triton.tools.experimental_descriptor
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
    import triton.tools.experimental_descriptor
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/triton_all_gather_matmul.py", line 9, in <module>
    import triton.tools.experimental_descriptor
    import triton.tools.experimental_descriptor
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
ModuleNotFoundError: No module named 'triton.tools.experimental_descriptor'
W1028 02:06:40.050000 1673947 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1674045 closing signal SIGTERM
W1028 02:06:40.051000 1673947 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1674047 closing signal SIGTERM
W1028 02:06:40.051000 1673947 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1674048 closing signal SIGTERM
W1028 02:06:40.052000 1673947 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1674049 closing signal SIGTERM
W1028 02:06:40.052000 1673947 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1674050 closing signal SIGTERM
W1028 02:06:40.052000 1673947 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1674051 closing signal SIGTERM
W1028 02:06:40.052000 1673947 torch/distributed/elastic/multiprocessing/api.py:908] Sending process 1674052 closing signal SIGTERM
E1028 02:06:40.085000 1673947 torch/distributed/elastic/multiprocessing/api.py:882] failed (exitcode: 1) local_rank: 1 (pid: 1674046) of binary: python3
Traceback (most recent call last):
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/bin/torchrun", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 357, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/run.py", line 936, in main
    run(args)
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/run.py", line 927, in run
    elastic_launch(
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 156, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/weka/home/omkar.pangarkar/symm-mem-recipes/.venv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 293, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
python3 FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-10-28_02:06:40
  host      : fs-mbz-gpu-873
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1674046)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
